language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm test
  - if [ -f src/variables/SiteData.jsx ]; then npm-run-all -p watch-css start-js; else cp src/variables/SiteData.jsx-sample src/variables/SiteData.jsx && npm run build; fi
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: develop

notifications:
  slack:
    secure: ImM7swNVyWU8Md6CeTz2t/+BvkhMaNp2U/2syV5M59CVUkxo9OUPF007zzz/kkTdnAHtARBCEM+6w2Nqeefht2Ew4ub1nnzhYC/c0ZjPEZdIzpAJQ9H/tL+j360C7fruVw/tqekl6Reg/oCjJEQPgVseM5602d1tl2kA4XXbzsHE95ZoCQ1X17hW8vBurRP0BcGisBPOudoEi4IOXRumbKylxi2qK1JfeoCjdgAiIVDWhTlZNVrI4QgiF7/7BRGV8gYAqQwuqPz64rmo1LQ3hpvwnDQdKIVVydmtg60DIpmgT1wISvKF3Zg19IFQIjUUJFCe24YaXJS4RTjiPqLuimDfurg+mPIzw49KsUKvZawwGr8v5idJMu8JqnEdTvDP2/Snxm6aBO6KYGriLvu2qpzeZbeUcSj9vF4g+/qFpFNlimgXtBl5uAPBSLG8hbEKw9ORJVwnNjL31ds3LUrsfeStRugL5bYPNyr+/zQs4JCqWskUxQgAzYWfH4qw6aCAnNJDCgtP3lS3A6XUOTtpRhjLgib+Hb6olARfomXKGNnppjA0o34+eaWhCHo+gJkOBcI7QEoJcOeZqbaEWFt2W7HTzG6mbC0XR5Hx3dYQJ19duZaxhVzA4tiY65erPdGXtD+ZuQzRB8pPtjJj7rmvo88JmU7JUbMoMU8Zn2cu8To=
