version: "2"
services:
  node:
    container_name: react-register
    image: "node:10"
    ports:
      - "3003:3000"
    restart: unless-stopped
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app:Z
    expose:
      - "3000"
    command: "yarn start"
